# Identificadores únicos del proyecto
sonar.projectKey=tu_proyecto_key
sonar.projectName=Tu Proyecto Veterinaria
sonar.projectVersion=1.0

# Rutas de código y tests
sonar.sources=app
sonar.tests=tests
sonar.exclusions=vendor/**, public/**, resources/**, database/**
sonar.sourceEncoding=UTF-8

# CONFIGURACIÓN CRÍTICA PARA COBERTURA
# Indica dónde leer el reporte de PHPUnit
sonar.php.coverage.reportPaths=coverage.xml
# Indica dónde leer el log de ejecución de tests
sonar.php.tests.reportPath=test-report.xml